---
title: "Code to Reproduce Figure from Serology for SARS-CoV-2: apprehensions, opportunities, and the path forward (Bryant et al, 2020)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message=FALSE,warning=FALSE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(scales)

## get positive predictive value
#' @param p - prevlance
#' @param sens - senstivity 
#' @param spec - specificity 
ppv <- function(p,sens,spec){
    sens * p / (sens * p + (1-spec)*(1-p))
}

## correction of seroprevalance by sens and spec
#' @param p - seroprevlance
#' @param sens - senstivity 
#' @param spec - specificity 
correct_sero_misclass <- function(p,sens,spec){
  pmin(pmax((p + (spec-1))/(sens+spec -1),0),1)
}
```

```{r}
## set up example test characteristics and prev
prev_seq = seq(0,1,by=.0001)
sens_spec = c("0.65_0.95","0.80_0.98","0.90_0.99")
sens =  c(.65,.80,.9)
spec=c(.95,.98,.99)

## create a grid of tests across the full prev sequence
mygrid <- expand.grid(p=prev_seq,sens_spec=sens_spec) %>% 
  as_tibble() %>%
  separate(sens_spec,c("sens","spec"),"_") %>% 
  mutate(
    sens = as.numeric(sens),
    spec=as.numeric(spec),
    test = paste0(round(sens*100,0),"% sens., ",round(spec*100,0),"% spec."),
    ppv = ppv(p,sens,spec), 
    est_sp = correct_sero_misclass(p,sens,spec))


## hack to get sqrt transformed axes to show zero point
mysqrt_trans <- function() {
    trans_new("mysqrt", 
              transform = base::sqrt,
              inverse = function(x) ifelse(x<0, 0, x^2),
              domain = c(0, Inf))
}

figa <- mygrid %>% ggplot(aes(x=p*100,y=ppv*100,color=test,group=test)) + geom_line()  + theme_bw()  + xlab("true seroprevalence (%)") + 
  ylab("positive predictive value (%)") + theme(legend.position = "bottom") + scale_color_brewer(palette = "Set2") + 
  scale_y_continuous(trans="mysqrt",breaks=c(0,1,5,10,20,30,50,70,100)) + 
  scale_x_continuous(trans="mysqrt",breaks=c(0,1,5,10,20,30,50,70,100)) + 
  expand_limits(x = 0,y=0) + 
     geom_rect(data=data.frame(xmin=0,xmax=15,ymin=0,ymax=100),inherit.aes = FALSE,
                                aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),alpha=.3)

  

figa
```

```{r}

figb <- mygrid %>% ggplot(aes(x=p*100,y=est_sp*100,color=test,group=test)) + geom_line() +  theme_bw() + xlab("true seroprevalence (%)") + 
  ylab("adjusted seroprevalence estimate (%)") + 
#  annotation_custom(ggplotGrob(zoomed_version), xmin = 0, xmax = 40, 
#                       ymin = 60, ymax = 100) +  
  geom_abline(slope=1, intercept = 0,col='lightgrey',lty=2) + 
  scale_y_continuous(trans="mysqrt",breaks=c(0,1,5,10,20,30,50,70,100)) + 
  scale_x_continuous(trans="mysqrt",breaks=c(0,1,5,10,20,30,50,70,100)) +
  theme(legend.position = "bottom") + scale_color_brewer(palette = "Set2") + 
   geom_rect(data=data.frame(xmin=0,xmax=15,ymin=0,ymax=100),inherit.aes = FALSE,
                                aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax),alpha=.3)

figb
```

```{r,fig.width=12}
g <- ggarrange(figa, 
               figb, 
               heights = c(3, 3),
          labels = c("A", "B"),
          ncol = 2, nrow = 1, align = "v",common.legend=TRUE)

g
```


```{r}
sessionInfo()
```
